### ISSUE TITLE
Using routes in other files causes redirection loop

### ISSUE THREAD

**Issue by JosephDuffy** [ericf/express-slash#6]
Hopefully I'm not being silly here, but I've had a play around with the code and it seem to be Express Slash causing this.

When I use a custom router in another file, and add it via the `use` method with a prefix, I get false positives that cause redirection loops.

For example, a simplified version of what I have is:

```
// Load the routes
var series = require('./routes/series');

// Use slash to add/remove trailing slashes
var slash = require('express-slash');
app.use(slash());

// Add the routes
app.use('/series/', series);
```

When I visit `/series/`, I am redirected to `/series`, then back to `/series/`, and a loop occurs.

I've tried to apply my basic knowledge and find a fix/change for this, but I can't figure it out myself. I can, however, confirm that it's the following check that is returning true:

```
route.methods[method] && layer.match(path)
```

Inside my `routes/series.js` I have `router.get('/:series/', function(req, res, next) { ... })`, which is the route that's triggering the false positive.

If any more information is required, let me know. Thanks for all the hard work and I'll keep trying to find a fix myself

**Comment by ericf** [comment]
Do you have the "strict routing" setting enabled on the series router?

**Comment by JosephDuffy** [comment]
Sorry, I failed to mention that in my `routes/series.js` file I have the follow at the top:

```
var express = require('express');
var app = express();
var router = express.Router({
    caseSensitive: app.get('case sensitive routing'),
    strict       : app.get('strict routing')
});
```

I have tried setting both of these values explicitly using `true`, rather than `app.get()`, but that does not seem to fix the issue.

**Comment by ericf** [comment]
@JosephDuffy to make it easier for me to debug, could you create a Gist of a simplified version of what you have that shows the problem? Thanks.

**Comment by JosephDuffy** [comment]
I can't recreate the example issue as above, but I have recreated an older issue that acts in the same way (infinite redirect).
Gist: https://gist.github.com/JosephDuffy/17d25b5ba354a2d005f1
Examples:
:thumbsup: /series -> /series/
:-1: /series/test -> (no redirect)
:-1: /about -> /about/
:thumbsup: /about/ -> /about

Removing either routes (i.e., commenting out lines 24 or 25 of app.js) fixes the issues for that route

**Comment by ericf** [comment]
Ah, so one thing is you should make sure that this middleware comes after your router.

**Comment by JosephDuffy** [comment]
I thought that the example showed the `app.use(slash());` call after the router setup (which I'm doing via `var routes = require('./index');`), but before they're added via `app.use(routes);`?
Moving `app.use(slash());` to after the `app.use()` calls with the routers causes /series serve /series/, and not redirect to /series/. This doesn't seem to be a Express Slash issue, though?
Sorry about my naivety of the situation, especially if this is in fact my fault.

**Comment by niftylettuce** [comment]
Perhaps this would have fixed your issue? https://github.com/niftylettuce/express-redirect-loop

**Comment by JosephDuffy** [comment]
I no longer use or maintain the project this issue was raised because of, so I'm not sure what the real solution would have been. More than likely it was my mistake :)

Closing for now, feel free to reopen.
